version: "3.8"

services:
  frontend-studies-database:
    container_name: frontend-studies-database
    env_file:
      - .env
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./volumes-mnt/database-data:/var/lib/postgresql/data
  frontend-studies-application:
    container_name: frontend-studies-application
    env_file:
      - .env
    build:
      context: ./app
    restart: unless-stopped
    links:
      - frontend-studies-database
    depends_on:
      - frontend-studies-database
    volumes:
      - ./volumes-mnt/static/media:/usr/src/frontend-studies-app/backend/media
      - ./volumes-mnt/static/tmp-files:/usr/src/frontend-studies-app/backend/tmp-files
      - ./volumes-mnt/static/frontend:/usr/src/frontend-studies-app/frontend
  frontend-studies-proxy:
    container_name: frontend-studies-proxy
    image: nginx:latest
    expose:
      - "${EXTERNAL_HTTP_PORT}"
      - "${EXTERNAL_HTTPS_PORT}"
    restart: always
    env_file:
      - .env
    volumes:
      - ./volumes-mnt/static/media:/usr/share/nginx/media:ro
      - ./volumes-mnt/static/frontend:/usr/share/nginx/frontend:ro
      - ./volumes-mnt/proxy/cert:/usr/share/nginx/cert:ro
      - ./volumes-mnt/proxy/acme:/usr/share/nginx/acme
      - ./volumes-mnt/proxy/templates:/etc/nginx/templates
    ports:
      - "${EXTERNAL_HTTP_PORT}:${EXTERNAL_HTTP_PORT}"
      - "${EXTERNAL_HTTPS_PORT}:${EXTERNAL_HTTPS_PORT}"
    depends_on:
      - frontend-studies-application
  frontend-studies-certbot:
    container_name: frontend-studies-certbot
    image: certbot/certbot:latest
    env_file:
      - .env
    command: certonly --webroot --webroot-path="/etc/webroot" --email="$EMAIL_USER" --agree-tos --no-eff-email -d "$SRV_NAME"
    volumes:
      - ./volumes-mnt/proxy/acme:/etc/webroot
      - ./volumes-mnt/proxy/cert:/etc/letsencrypt
    depends_on:
      - frontend-studies-proxy
