version: "3.8"

services:
  frontend-studies-database:
    container_name: frontend-studies-database
    env_file:
      - .env
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data:rw
  frontend-studies-application:
    container_name: frontend-studies-application
    env_file:
      - .env
    build:
      context: ./app
    restart: unless-stopped
    links:
      - frontend-studies-database
    depends_on:
      - frontend-studies-database
    volumes:
      - app-media:/usr/src/frontend-studies-app/media:rw
      - app-temp:/usr/src/frontend-studies-app/tmp-files:rw
      - frontend-static:/usr/share/frontend-static:rw
  frontend-studies-proxy:
    container_name: frontend-studies-proxy
    image: nginx:latest
    expose:
      - "${EXTERNAL_HTTP_PORT}"
      - "${EXTERNAL_HTTPS_PORT}"
    restart: always
    env_file:
      - .env
    volumes:
      - app-media:/usr/share/nginx/media:ro
      - frontend-static:/usr/share/nginx/frontend:ro
      - ./volumes-mnt/proxy/cert:/usr/share/nginx/cert:ro
      - ./volumes-mnt/proxy/acme:/usr/share/nginx/acme:rw
      - ./volumes-mnt/proxy/templates:/etc/nginx/templates:rw
    ports:
      - "${EXTERNAL_HTTP_PORT}:${EXTERNAL_HTTP_PORT}"
      - "${EXTERNAL_HTTPS_PORT}:${EXTERNAL_HTTPS_PORT}"
    depends_on:
      - frontend-studies-application
  frontend-studies-certbot:
    container_name: frontend-studies-certbot
    image: certbot/certbot:latest
    env_file:
      - .env
    command: certonly --webroot --webroot-path="/etc/webroot" --email="$EMAIL_USER" --agree-tos --no-eff-email -d "$SRV_NAME"
    volumes:
      - ./volumes-mnt/proxy/acme:/etc/webroot
      - ./volumes-mnt/proxy/cert:/etc/letsencrypt
    depends_on:
      - frontend-studies-proxy

volumes:
  database-data:
  frontend-static:
  app-media:
  app-temp: