name: frontend-studies-react-task
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code to runner
        uses: actions/checkout@v3

      - name: Set up JS environment
        uses: actions/setup-node@v3
        with:
          node-version: '16.13.1'

      - name: Install dependencies
        working-directory: app-frontend
        run: yarn install

      - name: Run tests
        working-directory: app-frontend
        run: yarn test

      - name: Archive test reports
