name: react-task
on:
  push:
    branches:
      - main
    paths:
      - 'app-backend/**'
      - 'app-frontend/**'
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code to runner
        uses: actions/checkout@v3

      - name: Set up JS environment
        uses: actions/setup-node@v3
        with:
          node-version: '16.13.1'

      - name: Install email server dependencies
        working-directory: email-server
        run: yarn install

      - name: Run email server
        working-directory: email-server
        run: yarn serve

      - name: Run backend
        uses: ./app-backend/.github/actions/run-backend

      - name: Install frontend dependencies
        working-directory: app-frontend
        run: yarn install

      - name: Run frontend
        working-directory: app-frontend
        run: yarn start

      - name: Install test dependencies
        working-directory: test-engine
        run: yarn install

      - name: Run tests
        working-directory: test-engine
        run: yarn test

      - name: Archive test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: reports
          if-no-files-found: ignore
